### ISSUE TITLE
 Calling useOneTap with this dependency package is always onError

### ISSUE THREAD

**Issue by dfangdev** [wavezync/vue3-google-signin#79]
**Describe the bug**.
nuxt3 versioin 3.8.0  ,
nuxt-vue3-google-signin  version 0.0.11

**To Reproduce**
1. useOneTap({
  onSuccess: (response: CredentialResponse) => {
    console.log("Success:", response);
  },
  onError: (e: void) => console.error("Error with One Tap Login",),
  // options
});
2. Enter the page and Google one-click login pops up. Click to log in and always receive the onError callback.
3.Tip Error with One Tap Login

**Screenshots**
Expect to go to onSuccess.

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, safari，google]

**Comment by lzdyes** [comment]
I also encountered this problem. When I integrated Google One Tap and tested it in Chrome on macOS, the onError callback was always triggered, but there was no detailed error message. So, I had to debug it myself. I found that the login was actually successful, because when it called back to the callback, there was no clientId field, which caused the plugin to determine that it was not successful.

https://github.com/wavezync/vue3-google-signin/blob/7c15d7d9e60697c0fab2c0c3a23e97443e19039e/src/composables/useOneTap.ts#L222C33-L222C41

<img width="559" alt="image" src="https://github.com/user-attachments/assets/c2a37ec3-0300-48e4-bdbb-93de979dba86">

**Comment by lzdyes** [comment]
> I also encountered this problem. When I integrated Google One Tap and tested it in Chrome on macOS, the onError callback was always triggered, but there was no detailed error message. So, I had to debug it myself. I found that the login was actually successful, because when it called back to the callback, there was no clientId field, which caused the plugin to determine that it was not successful.
> 
> https://github.com/wavezync/vue3-google-signin/blob/7c15d7d9e60697c0fab2c0c3a23e97443e19039e/src/composables/useOneTap.ts#L222C33-L222C41
> 
> <img alt="image" width="559" src="https://private-user-images.githubusercontent.com/26008805/351737346-c2a37ec3-0300-48e4-bdbb-93de979dba86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Mjg3ODgsIm5iZiI6MTcyMTgyODQ4OCwicGF0aCI6Ii8yNjAwODgwNS8zNTE3MzczNDYtYzJhMzdlYzMtMDMwMC00OGU0LWJkYmItOTNkZTk3OWRiYTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDEzNDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YWIyZGFhZWNmMGE4MDE4ZTc1MDg5M2I2NDNlNGY1MjdmNjYyMGZiYzdiODNmNzk1MmI2N2JmMTg4OTE2YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HA-sqo2dWFQm60Bd2oFFd5zJDnfIqUN1-vBS4k8Oyxk">

@wavezync Could you take a look at this issue and fix this scenario as well?
